base_url = 'https://newsapi.org/v2/{type}?apiKey={api_key}&pageSize=100'

countries = {'ar': 'Argentina', 'au': 'Australia', 'at': 'Austria', 'be': 'Belgium', 'br': 'Brazil', 'bg': 'Bulgaria',
             'ca': 'Canada', 'cn': 'China', 'co': 'Colombia', 'cu': 'Cuba', 'cz': 'Czech Republic', 'eg': 'Egypt',
             'fr': 'France', 'de': 'Germany', 'gr': 'Greece', 'hk': 'Hong Kong', 'hu': 'Hungary', 'in': 'India',
             'id': 'Indonesia', 'ie': 'Ireland', 'il': 'Israel', 'it': 'Italy', 'jp': 'Japan', 'lv': 'Latvia',
             'lt': 'Lithuania', 'my': 'Malaysia', 'mx': 'Mexico', 'ma': 'Morocco', 'nl': 'Netherlands',
             'nz': 'New Zealand', 'ng': 'Nigeria', 'no': 'Norway', 'ph': 'Philippines', 'pl': 'Poland',
             'pt': 'Portugal', 'ro': 'Romania', 'ru': 'Russia', 'sa': 'Saudi Arabia', 'rs': 'Serbia', 'sg': 'Singapore',
             'sk': 'Slovakia', 'si': 'Slovenia', 'za': 'South Africa', 'kr': 'South Korea', 'se': 'Sweden',
             'ch': 'Switzerland', 'tw': 'Taiwan', 'th': 'Thailand', 'tr': 'Turkey', 'ae': 'UAE', 'ua': 'Ukraine',
             'gb': 'United Kingdom', 'us': 'United States', 've': 'Venuzuela'}

sources = {'abc-news': 'ABC News', 'abc-news-au': 'ABC News (AU)', 'aftenposten': 'Aftenposten',
           'al-jazeera-english': 'Al Jazeera English', 'ansa': 'ANSA.it', 'argaam': 'Argaam',
           'ars-technica': 'Ars Technica', 'ary-news': 'Ary News', 'associated-press': 'Associated Press',
           'australian-financial-review': 'Australian Financial Review', 'axios': 'Axios', 'bbc-news': 'BBC News',
           'bbc-sport': 'BBC Sport', 'bild': 'Bild', 'blasting-news-br': 'Blasting News (BR)',
           'bleacher-report': 'Bleacher Report', 'bloomberg': 'Bloomberg', 'breitbart-news': 'Breitbart News',
           'business-insider': 'Business Insider', 'business-insider-uk': 'Business Insider (UK)',
           'buzzfeed': 'Buzzfeed', 'cbc-news': 'CBC News', 'cbs-news': 'CBS News', 'cnbc': 'CNBC', 'cnn': 'CNN',
           'cnn-es': 'CNN Spanish', 'crypto-coins-news': 'Crypto Coins News', 'daily-mail': 'Daily Mail',
           'der-tagesspiegel': 'Der Tagesspiegel', 'die-zeit': 'Die Zeit', 'el-mundo': 'El Mundo',
           'engadget': 'Engadget', 'entertainment-weekly': 'Entertainment Weekly', 'espn': 'ESPN',
           'espn-cric-info': 'ESPN Cric Info', 'financial-post': 'Financial Post', 'financial-times': 'Financial Times',
           'focus': 'Focus', 'football-italia': 'Football Italia', 'fortune': 'Fortune', 'four-four-two': 'FourFourTwo',
           'fox-news': 'Fox News', 'fox-sports': 'Fox Sports', 'globo': 'Globo', 'google-news': 'Google News',
           'google-news-ar': 'Google News (Argentina)', 'google-news-au': 'Google News (Australia)',
           'google-news-br': 'Google News (Brasil)', 'google-news-ca': 'Google News (Canada)',
           'google-news-fr': 'Google News (France)', 'google-news-in': 'Google News (India)',
           'google-news-is': 'Google News (Israel)', 'google-news-it': 'Google News (Italy)',
           'google-news-ru': 'Google News (Russia)', 'google-news-sa': 'Google News (Saudi Arabia)',
           'google-news-uk': 'Google News (UK)', 'goteborgs-posten': 'Göteborgs-Posten',
           'gruenderszene': 'Gruenderszene', 'hacker-news': 'Hacker News', 'handelsblatt': 'Handelsblatt',
           'ign': 'IGN', 'il-sole-24-ore': 'Il Sole 24 Ore', 'independent': 'Independent', 'infobae': 'Infobae',
           'info-money': 'InfoMoney', 'la-gaceta': 'La Gaceta', 'la-nacion': 'La Nacion',
           'la-repubblica': 'La Repubblica', 'le-monde': 'Le Monde', 'lenta': 'Lenta', 'lequipe': "L'equipe",
           'les-echos': 'Les Echos', 'liberation': 'Libération', 'marca': 'Marca', 'mashable': 'Mashable',
           'medical-news-today': 'Medical News Today', 'metro': 'Metro', 'mirror': 'Mirror', 'msnbc': 'MSNBC',
           'mtv-news': 'MTV News', 'mtv-news-uk': 'MTV News (UK)', 'national-geographic': 'National Geographic',
           'national-review': 'National Review', 'nbc-news': 'NBC News', 'news24': 'News24',
           'new-scientist': 'New Scientist', 'news-com-au': 'News.com.au', 'newsweek': 'Newsweek',
           'new-york-magazine': 'New York Magazine', 'next-big-future': 'Next Big Future', 'nfl-news': 'NFL News',
           'nhl-news': 'NHL News', 'nrk': 'NRK', 'politico': 'Politico', 'polygon': 'Polygon', 'rbc': 'RBC',
           'recode': 'Recode', 'reddit-r-all': 'Reddit /r/all', 'reuters': 'Reuters', 'rt': 'RT', 'rte': 'RTE',
           'rtl-nieuws': 'RTL Nieuws', 'sabq': 'SABQ', 'spiegel-online': 'Spiegel Online',
           'svenska-dagbladet': 'Svenska Dagbladet', 't3n': 'T3n', 'talksport': 'TalkSport', 'techcrunch': 'TechCrunch',
           'techcrunch-cn': 'TechCrunch (CN)', 'techradar': 'TechRadar',
           'the-american-conservative': 'The American Conservative', 'the-economist': 'The Economist',
           'the-globe-and-mail': 'The Globe And Mail', 'the-guardian-au': 'The Guardian (AU)',
           'the-guardian-uk': 'The Guardian (UK)', 'the-hill': 'The Hill', 'the-hindu': 'The Hindu',
           'the-huffington-post': 'The Huffington Post', 'the-irish-times': 'The Irish Times',
           'the-jerusalem-post': 'The Jerusalem Post', 'the-lad-bible': 'The Lad Bible',
           'the-new-york-times': 'The New York Times', 'the-next-web': 'The Next Web',
           'the-sport-bible': 'The Sport Bible', 'the-telegraph': 'The Telegraph',
           'the-times-of-india': 'The Times of India', 'the-verge': 'The Verge',
           'the-wall-street-journal': 'The Wall Street Journal', 'the-washington-post': 'The Washington Post',
           'the-washington-times': 'The Washington Times', 'time': 'Time', 'usa-today': 'USA Today',
           'vice-news': 'Vice News', 'wired': 'Wired', 'wired-de': 'Wired.de', 'wirtschafts-woche': 'Wirtschafts Woche',
           'xinhua-net': 'Xinhua Net', 'ynet': 'Ynet'}

categories = ['business', 'entertainment', 'general', 'health', 'science', 'sports', 'technology']

languages = ['ar', 'de', 'en', 'es', 'fr', 'he', 'it', 'nl', 'no', 'pt', 'ru', 'se', 'ud', 'zh']

sortBys = ['relevancy', 'popularity', 'publishedAt', 'relevancy', 'popularity', 'publishedAt']
